# Generated by Django 2.1.3 on 2018-11-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('intro', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('uri', models.URLField()),
                ('description', models.TextField(max_length=300)),
                ('file', models.FileField(upload_to='uploads/ontologies/')),
                ('authors', models.ManyToManyField(blank=True, to='search_app.Author')),
            ],
        ),
    ]
