# Generated by Django 2.1.3 on 2018-11-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='intro',
            new_name='introduction',
        ),
        migrations.AlterField(
            model_name='ontology',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
