# Generated by Django 2.1.3 on 2018-11-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_auto_20181120_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontology',
            name='license',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
