# Generated by Django 2.1.3 on 2018-11-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_ontology_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontology',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/ontologies/'),
        ),
    ]
