# Generated by Django 2.1.3 on 2018-11-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0004_auto_20181120_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='introduction',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
